### ISSUE TITLE
OpenShift 4.11 requires `clusterlogging.collection.type` to be set explicitly

### ISSUE THREAD

**Issue by corvus-ch** [appuio/component-openshift4-logging#68]
## Steps to Reproduce the Problem

  1. On OpenShift 4.11, upgrade hosted logging to ≥ 5.5.2

## Actual Behavior
Collector pods keep being restarted.

{"_ts":"2022-10-18T12:18:16.867228372Z","_level":"0","_component":"cluster-logging-operator","_message":"clusterlogforwarder-controller error updating status","_error":{"msg":"Operation cannot be fulfilled on clusterlogforwarders.logging.openshift.io \"instance\": the object has been modified; please apply your changes to the latest version and try again"}}

## Expected Behavior
Collector pods keeps running

## Suggested implementation

https://access.redhat.com/solutions/6976455 suggests to explicitly set:

```yaml
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
...
  name: instance
  namespace: openshift-logging
...
spec:
  collection:
    type: fluentd
    logs:
      type: fluentd
```

For `spec.collection.logs.type` this is already done (https://github.com/appuio/component-openshift4-logging/blob/679ea778f84bed46e2b57502e7b8e62e68b6a581/class/defaults.yml#L58). Adding `spec.collection.type` is straight forward.
