### ISSUE TITLE
Add default network policy to allow communication between elasticsearch-operator and ns openshift-logging

### ISSUE THREAD

**Issue by Sabrinibini** [appuio/component-openshift4-logging#7]
## Context
When installing elasticsearch-operator in the official namespace openshift-operators-redhat, Elasticsearch is not accessible. There are default network policies allow-from-other-namespaces and allow-from-same-namespace in place which allow ingress traffic and traffic within a ns. Communication between ns is not allowed. The elasticsearch-operator is installed in ns openshift-operators-redhat and needs access to elasticsearch in ns openshift-logging. 

A network policy should be implemented, which should allow this communication.

**Comment by megian** [comment]
Example:
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-elasticsearch-operator-from-openshift-operators-redhat
  namespace: openshift-logging
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: openshift-operators-redhat
    - podSelector:
        matchLabels:
          name: elasticsearch-operator
  podSelector:
    matchLabels:
      component: elasticsearch
  policyTypes:
  - Ingress
```
